sudo: false
language: ruby
rvm:
  - 2.4.3
services:
  - postgresql
before_script:
  - psql -c 'create database trello_echo_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:setup
  - bundle exec rake
notifications:
  email:
    - travisci@dennmart.com
