default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: trello_echo_development

test:
  <<: *default
  database: trello_echo_test

production:
  <<: *default
  username: trello_echo
  url: <%= ENV['TRELLO_ECHO_DATABASE_URL'] %>
