default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: trello_echo_development

test:
  <<: *default
  database: trello_echo_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
